# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1        
        with:
          dotnet-version: '6.0.101'
      - run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./coverage/opencover.xml
      - run: dotnet publish ./src/Arthur.Verzele.FeatureMatching.WebApi/Arthur.Verzele.FeatureMatching.WebApi.csproj --self-contained true --output ./win-x64/featureMatching -c Release -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true
      - name: Upload WebApp1 Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Publish win-x64 FeatureMatching
          path: ./win-x64/featureMatching
